language: node_js
node_js:
- '0.10'
sudo: false
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: A841uu+WORDCzkE+gRQ+drIuUDomcWza/nt/8sgZhuCY4l9bPfmr/wYqYy8agGb/E0A7fGb4SLP5nClIgwM/aBYX2ml8GigYbuEANNBpmHBuxShUy43qB0PpV2o7D6zD9iCnrzupdSsvivZAu5HnTqe5TtaVMg68JzNVCPXM9eI=
  on:
    tags: true
    all_branches: true
