language: node_js
node_js:
- '0.10'
sudo: false
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: tEf3FEKGBTYHsaCz9LvffGAcKjwZK7QXCwP1gLS75Mag+cRvA9NU45eFFxA5K5VCtL9jdBnf1dB9tUtCCKTXzhFzcy8eySZTZruClhsg8weoVfdyrLco1A2i9soaoN6UhcetAT+iVkKL6HSvt1VDwvo8LdtKXjbSqVyYtuCk87k=
  on:
    tags: true
    repo: octoblu/meshblu-twitter-stream
