language: node_js
node_js:
- '0.10'
use_sudo: false
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: "KTtATikAa1tRraMYX8WGE50Xz6mhn+BHSGaDY6b5F8b0Z5ltzvZXLvJDCl/Ibdwu9xrKTt9JukzT3pijRxi/yeNbvbaoGtRpWkBy+wFt/wZOxWj4n4lg8X5xBWt4YL5hKIankyaN9Y6yYBRU21RQOjWXAbgfj72x15QHWFSTn6U="
  on:
    tags: true
    all_branches: true
